name: My First Workflow
on: 
  schedule:
    - cron: '34 11 * * 6'

  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello Github Actions!"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the follwing files:"
          tree
